export const manufacturers = [
  "Pfizer",
  "Johnson & Johnson",
  "Roche",
  "Novartis",
  "Merck",
  "Sanofi",
  "Mankind PVT Ltd.",
  "GSK",
  "Bayer",
  "AbbVie",
  "Moderna",
  "AstraZeneca",
  "Eli Lilly",
  "Bristol-Myers Squibb",
  "Biocon",
  "Dr. Reddy's",
  "Sun Pharma",
  "Lupin",
  "Cipla",
  "Zydus Cadila",
];
